workflows:
  hello-world:
    name: Hello world workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.16.3
      xcode: 15
      cocoapods: 1.12.0
    scripts: 
      - flutter emulators --launch emulator
      - make it