workflows:
  hello-world:
    name: Hello world workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.13.9
      xcode: 15
      cocoapods: 1.11.3
    scripts: 
      - flutter emulators --launch apple_ios_simulator
      - make it